# Hint: try to change the URL address. to 2**38
# url = http://www.pythonchallenge.com/pc/def/0.html
import webbrowser


def replace_url(url, old_url, url_to_replace):
    """
    Replace a specific string in a URL with a new string and open the modified URL in a web browser.

    Parameters:
        url (str): The original URL.
        old_url (str): The string in the original URL that will be replaced.
        url_to_replace (str): The string that will be used to replace `old_url` in the original URL.

    Returns:
        str: The modified URL.
    """

    new_url = url.replace(old_url, url_to_replace)
    webbrowser.open(new_url)
    return new_url


def main():
    """
    Open a web browser and navigate to a URL that is generated by replacing a specific string in the original URL with a new string.
    The new string is generated by using the Python `f-string` feature to insert the value of `2**38` into the string.
    """

    url = 'http://www.pythonchallenge.com/pc/def/0.html'
    n = 2 ** 38
    new_url = replace_url(url, '0.html', f'{n}.html')
    print(new_url)


if __name__ == "__main__":
    main()
